/*
# Add AI Titles and Promoted ad-rate to bulk_runs

## Overview
Adds the two remaining Bulk Add fields: whether to use AI-generated titles
and item specifics for this batch, and the ad rate (%) to use when adding
published listings to eBay's Promoted Listings.

## Modified Tables
1. `bulk_runs`
   - `ai_titles` (boolean) — if true, title + item specifics are generated by AI instead of using the raw Amazon data
   - `ad_rate` (numeric) — Promoted Listings bid percentage to apply when `promoted` is true
*/

ALTER TABLE bulk_runs
  ADD COLUMN IF NOT EXISTS ai_titles boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS ad_rate numeric NOT NULL DEFAULT 3;
